name: 'NX Gather Outputs'
description: 'Finds all outputs for a specified NX target'
author: 'WonderPanda'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  targetName:
    description:
      'The name of the NX target for which to gather outputs (eg. codegen)'
    required: true
    default: codegen

# Define your outputs here.
outputs:
  paths:
    description: The paths of all outputs for the specified target

runs:
  using: node20
  main: dist/index.js
